version: '3.1'

services:
  webapp:
    build: ./webapp
    restart: always
    environment:
      AIRELLA_DOMAIN: "https://airella.cyfrogen.com"
    env_file: ../airella-private/secret_webapp.env
    ports:
    - "8880:8080"
    depends_on:
    - database
  database:
    image: postgres:12.4
    container_name: airella-database
    restart: always
    env_file: ../airella-private/secret_database.env
    volumes:
      - ./db_data:/var/lib/postgresql/data:z
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql:z
    ports:
      - "5432:5432"
  gsm-extender:
    build: ./gsm-extender
    restart: always
    ports:
    - "8881:8080"
    depends_on:
    - webapp
