version: '3.1'

services:
  webapp:
    build: ./webapp
    restart: always
    ports:
    - "8081:8081"
    depends_on:
    - database
  database:
    image: postgres
    container_name: airella-database
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db_data:/var/lib/postgresql/data:z
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql:z
    ports:
      - "5432:5432"
