version: '3.1'

services:
  webapp:
    build: ./webapp
    restart: always
    environment:
      EMAIL_LOGIN: "cat /run/secrets/email_login"
      EMAIL_PASSWORD: "cat /run/secrets/email_password"
      DOMAIN: "http://airella.cyfrogen.com"
    ports:
    - "8080:8080"
    depends_on:
    - database
  database:
    image: postgres
    container_name: airella-database
    restart: always
    environment:
      POSTGRES_PASSWORD: "cat /run/secrets/database_password"
    volumes:
      - ./db_data:/var/lib/postgresql/data:z
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql:z
    ports:
      - "5432:5432"

secrets:
   database_password:
     file: ../airella-private/database_password.txt
   email_login:
     file: ../airella-private/email_login.txt
   email_password:
     file: ../airella-private/email_password.txt
