version: '3.1'

services:
  webapp:
    build: ./webapp
    restart: always
    environment:
      DOMAIN: "http://airella.cyfrogen.com"
    env_file: ../airella-private/secret.env
    ports:
    - "8080:8080"
    depends_on:
    - database
  database:
    image: postgres
    container_name: airella-database
    restart: always
    environment:
      POSTGRES_PASSWORD: "cat /run/secrets/database_password"
    volumes:
      - ./db_data:/var/lib/postgresql/data:z
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql:z
    ports:
      - "5432:5432"
